// src/lib/explore/scientist-images.ts
//
// GENERATED by scripts/scientist-images.mts — do not edit by hand.
// Run `npm run explore:scientist-images` to rebuild this module and the
// files it names. Every licence below was re-checked against Wikimedia on
// that run.
//
// A scientist absent from this map has no picture, on purpose, and their
// card renders with no picture and no placeholder:
//
// **marie-maynard-daly** — No free portrait. commons:File:Marie Maynard Daly.jpg is tagged public domain,
//   but its stated provenance is a 1942 Queens College yearbook reached through a
//   blog mirror, with no evidence of non-renewal recorded — a 1942 US copyright claim
//   nobody has actually checked. It is also 250x290, below the 306 px this slot needs
//   on the narrowest phone. English Wikipedia does not use it either. Her work was
//   not used instead: the nuclear half of her card is histones, and every free nucleosome
//   diagram on Commons is a ribbon model that says nothing a reader at 12 can follow,
//   while the arteries half is cholesterol — which is the molecule card she is paired
//   with that week, so it would put the same picture on the page twice. A named,
//   sourced portrait would be very welcome; this is a real gap and not a settled
//   decision.

import type { ExploreScientistImage } from './types';

export const SCIENTIST_IMAGES: Record<string, ExploreScientistImage> = {
  // An official portrait, already cropped to head and shoulders.
  'akira-yoshino': {
    src: '/explore/scientists/akira-yoshino.jpg',
    width: 900,
    height: 1200,
    subject: 'person',
    credit: {
      author: "大臣官房人事課 (Minister’s Secretariat Personnel Division, Japan)",
      licence: "CC BY 4.0",
      licenceUrl: "https://creativecommons.org/licenses/by/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Akira_Yoshino_20170920_(cropped_2).jpg",
    },
  },
  // From the ETH image archive, which released its portrait series freely.
  'alfred-werner': {
    src: '/explore/scientists/alfred-werner.jpg',
    width: 900,
    height: 1321,
    subject: 'person',
    credit: {
      author: "ETH-Bibliothek Zürich, Bildarchiv",
      licence: "CC BY-SA 3.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Alfred_Werner_ETH-Bib_Portr_09965.jpg",
    },
  },
  // During the 2011 Nobel interviews.
  'dan-shechtman': {
    src: '/explore/scientists/dan-shechtman.jpg',
    width: 900,
    height: 1350,
    subject: 'person',
    credit: {
      author: "Holger Motzkau",
      licence: "CC BY-SA 3.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Nobel_Prize_2011-Nobel_interviews_KVA-DSC_8039.jpg",
    },
  },
  // A large, clean studio portrait.
  'fritz-haber': {
    src: '/explore/scientists/fritz-haber.jpg',
    width: 900,
    height: 1207,
    subject: 'person',
    credit: {
      author: "Unknown photographer — Spaarnestad Photo",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Portret_van_Professor_Fritz_Haber%2C_een_chemicus_uit_Duitsland_(foto_1918-_1934)%2C_SFA002023057.jpg",
    },
  },
  // His own 1902 memorandum drawing cubical atoms — the ancestor of the dot diagram his card is about. No free portrait exists.
  'gilbert-lewis': {
    src: '/explore/scientists/gilbert-lewis.jpg',
    width: 900,
    height: 1009,
    subject: 'work',
    credit: {
      author: "Gilbert N. Lewis",
      licence: "Public domain",
      sourceUrl: "https://en.wikipedia.org/wiki/File:Lewis-cubic-notes.jpg",
    },
  },
  // A 1960s portrait, from the period of the Nobel.
  'giulio-natta': {
    src: '/explore/scientists/giulio-natta.jpg',
    width: 648,
    height: 878,
    subject: 'person',
    credit: {
      author: "Unknown photographer (Mondadori Publishers)",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Giulio_Natta_1960s.jpg",
    },
  },
  // The only free portrait of her that exists. Small — 180 px wide, so it is not enlarged and is soft at full width on a phone.
  'johanna-dobereiner': {
    src: '/explore/scientists/johanna-dobereiner.jpg',
    width: 180,
    height: 250,
    subject: 'person',
    credit: {
      author: "Unknown — via Wikimedia Commons",
      licence: "CC BY-SA 4.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Johanna-D%C3%B6bereiner.jpg",
    },
  },
  // Demonstrating her own apparatus — the portrait and the work in one frame.
  'katharine-blodgett': {
    src: '/explore/scientists/katharine-blodgett.jpg',
    width: 900,
    height: 882,
    subject: 'person',
    credit: {
      author: "Smithsonian Institution, via Flickr Commons",
      licence: "No known copyright restrictions",
      licenceUrl: "https://www.flickr.com/commons/usage/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Katharine_Burr_Blodgett_(1898-1979)%2C_demonstrating_equipment_in_lab.jpg",
    },
  },
  // At the bench. The Smithsonian releases it with no known restrictions.
  'kathleen-lonsdale': {
    src: '/explore/scientists/kathleen-lonsdale.jpg',
    width: 900,
    height: 1279,
    subject: 'person',
    credit: {
      author: "F. C. Livingstone — Smithsonian Institution, via Flickr Commons",
      licence: "No known copyright restrictions",
      licenceUrl: "https://www.flickr.com/commons/usage/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kathleen_Yardley_Lonsdale_(1903-1971).jpg",
    },
  },
  // The standard portrait.
  'kikunae-ikeda': {
    src: '/explore/scientists/kikunae-ikeda.jpg',
    width: 821,
    height: 1200,
    subject: 'person',
    credit: {
      author: "Unknown photographer",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Kikunae_Ikeda.jpg",
    },
  },
  // A 2019 portrait, large and sharp.
  'margarita-salas': {
    src: '/explore/scientists/margarita-salas.jpg',
    width: 900,
    height: 1157,
    subject: 'person',
    credit: {
      author: "LaMèreVeille",
      licence: "CC BY-SA 4.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Margarita_Salas_Falgueras_062019.jpg",
    },
  },
  // The NYWT&S press photograph — the collection was dedicated to the public.
  'maria-telkes': {
    src: '/explore/scientists/maria-telkes.jpg',
    width: 900,
    height: 1121,
    subject: 'person',
    credit: {
      author: "New York World-Telegram and the Sun staff photographer",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Maria_Telkes_NYWTS.jpg",
    },
  },
  // The 1912 Nobel portrait.
  'paul-sabatier': {
    src: '/explore/scientists/paul-sabatier.jpg',
    width: 280,
    height: 396,
    subject: 'person',
    credit: {
      author: "Nobel Foundation",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Paul_Sabatier.jpg",
    },
  },
  // The only free portrait of her on Commons.
  'reatha-clark-king': {
    src: '/explore/scientists/reatha-clark-king.jpg',
    width: 617,
    height: 1033,
    subject: 'person',
    credit: {
      author: "VocalEssence Ensemble Singers",
      licence: "CC BY-SA 2.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Reatha_King_2009.jpg",
    },
  },
  // The standard portrait. Small, but it is the one that exists.
  'soren-sorensen': {
    src: '/explore/scientists/soren-sorensen.jpg',
    width: 248,
    height: 362,
    subject: 'person',
    credit: {
      author: "Unknown photographer",
      licence: "Public domain",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:SPL_Sorensen.jpg",
    },
  },
  // In the lab, 1986. The source is a TIFF and is converted to JPEG.
  'stephanie-kwolek': {
    src: '/explore/scientists/stephanie-kwolek.jpg',
    width: 404,
    height: 525,
    subject: 'person',
    credit: {
      author: "Science History Institute",
      licence: "CC BY-SA 3.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Stephanie_Kwolek_1986.TIF",
    },
  },
  // At the 2018 Crafoord Prize. The best-lit free portrait of her.
  'susan-solomon': {
    src: '/explore/scientists/susan-solomon.jpg',
    width: 900,
    height: 1125,
    subject: 'person',
    credit: {
      author: "Bengt Nyman",
      licence: "CC BY 2.0",
      licenceUrl: "https://creativecommons.org/licenses/by/2.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Crafoord_Prize_EM1B0739_(28456528038).jpg",
    },
  },
  // At the 2015 Nobel week, cropped to the portrait.
  'tu-youyou': {
    src: '/explore/scientists/tu-youyou.jpg',
    width: 900,
    height: 1345,
    subject: 'person',
    credit: {
      author: "Bengt Nyman",
      licence: "CC BY 2.0",
      licenceUrl: "https://creativecommons.org/licenses/by/2.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:D810_4987_Tu_Youyou%2C_medicine_(22945001843)_(cropped).jpg",
    },
  },
  // From the same ETH archive series as Werner.
  'vladimir-prelog': {
    src: '/explore/scientists/vladimir-prelog.jpg',
    width: 438,
    height: 600,
    subject: 'person',
    credit: {
      author: "ETH-Bibliothek Zürich, Bildarchiv",
      licence: "CC BY-SA 3.0",
      licenceUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Vladimir_Prelog_ETH-Bib_Portr_00214.jpg",
    },
  },
};
